repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        # Exclude README.md and content/ directory
        files: ^(?!README\.md|content/).*\.(md|yaml|yml|py|go|mod|sum|cpp|hpp|tpp)$
    -   id: end-of-file-fixer
        # Exclude README.md and content/ directory
        files: ^(?!README\.md|content/).*\.(md|yaml|yml|py|go|mod|sum|cpp|hpp|tpp)$
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        files: "\\.(py)$"
        args: [--config=pyproject.toml]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        files: "\\.(py)$"
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        files: "\\.(py)$"
        args: [--rcfile=pyproject.toml]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        files: "\\.(py)$"
